### ISSUE TITLE
Is preprocessing.ipynb available?

### ISSUE THREAD

**Issue by jeanmonet** [Ying-Lab/scIBD#1]
Hi,

Thank you for your work and for uploading the code.

In the file https://github.com/Ying-Lab/scIBD/blob/master/scripts/Description.txt  there is mention of some `preprocessing.ipynb` which supposedly covers the preprocessing steps required to obtain the input to scIDB, ie the count matrix.

Is it possible to make this notebook available?

**Comment by Ying-Lab** [comment]
We appreciate your notice on our work and we apologize for missing the preprocessing scripts. The preprocessing pipeline mainly follows the pipenline in https://github.com/r3fang/snATAC, which demands several dependency tools, including bwa (alignment), samtools (sort), snATAC/SnapATAC (quality control & creating matrix),  MACS3 (call peak) and sinto (convert BAM to fragment). 

Considering that the BAM files and fragment files are the most frequently-used files after single-cell sequencing, we start with such file formats. The detailed preprocessings will be presented in a Linux shell script, while the corresponding tools may be installed at advance.
