### ISSUE TITLE
reject detected doublets

### ISSUE THREAD

**Issue by ChengWan9** [Ying-Lab/scIBD#2]
Thanks for your great work! But I have a question about if a droplet will not change once it is detected as a doublet? And what does this code mean below? Why droplets whose 'label_refer != 0.05' is not doublet? Wouldn't there be any other numbers from 0-0.1 other than 0.05.
![image](https://github.com/Ying-Lab/scIBD/assets/143673887/fcd64e86-c8e6-490b-b103-fae8c0a5cd8e)

**Comment by Ying-Lab** [comment]
Hi!
   Sorry for the serious delay. The maintainer was in some issue in the last few months. I have updated the comments in the latest codes. 
   The label of a droplet (doublet or others) is temporary in one iteration, which only influences the next iteration, including the clustering and the doublet score calculation. The final determination of a droplet to be a doublet must refer to all the iterations (the mean doublet scores across all iterations). 
    For the second point, 'label_refer != 0.05' is the remained codes in one aborted version.  In this version, the predicted doublets in one iteration will be discarded by a tuned rejection criterion, and will be assigned with a 0.05 label to distingush these droplets. This version has beed dropped. For that It is almost impossible for a normalized doublet score to be exactly 0.05, the codes have none matter on the final results. 
Best wishes
Scotty Zhang

**Comment by ChengWan9** [comment]
Thanks for your reply
